[package]
name = "fuzzer-objdump"
version = "0.1.0"
authors = ["Roi Martin <jroi.martin@gmail.com>"]
edition = "2018"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
riscv-emu = { path = "../riscv-emu" }
